export default {
  PROMESSA_LOBINHO: 'PROMESSA_LOBINHO',
  PROMESSA_ESCOTEIRA: 'PROMESSA_ESCOTEIRA',

  ESCALADA: 'ESCALADA',
  CONQUISTA: 'CONQUISTA',
  AZIMUTE: 'AZIMUTE',
  IMMA_SENIOR: 'IMMA_SENIOR',
  CONE_SUL_SENIOR: 'CONE_SUL_SENIOR',
  LUSOFONIA_SENIOR: 'LUSOFONIA_SENIOR',
  DESAFIO_COMUNITARIO: 'DESAFIO_COMUNITARIO',
  MATEIRO: 'MATEIRO',
  AERONAUTA: 'AERONAUTA',
  NAVAL: 'NAVAL',
  CORDAO_DESAFIO_SENIOR: 'CORDAO_DESAFIO_SENIOR',
  CORDAO_DOURADO: 'CORDAO_DOURADO',
  ESCOTEIRO_PATRIA: 'ESCOTEIRO_PATRIA'
}
