export default {
  ESPECIALIDADE: 'ESPECIALIDADE',
  CULTURA: 'CULTURA',
  SERVICOS: 'SERVICOS',
  CIENCIA_TECNOLOGIA: 'CIENCIA_TECNOLOGIA',
  HABILIDADES_ESCOTEIRAS: 'HABILIDADES_ESCOTEIRAS',
  DESPORTOS: 'DESPORTOS',

  PROMESSA_ESCOTEIRA_LOBINHO: 'PROMESSA_ESCOTEIRA_LOBINHO',
  PROGRESSAO_PATATENRA_SALTADOR: 'PROGRESSAO_PATATENRA_SALTADOR',
  PROGRESSAO_RASTREADOR_CACADOR

  PROMESSA_ESCOTEIRA_ESCOTEIRO: 'PROMESSA_ESCOTEIRA_SENIOR',
  PROGRESSAO_PISTA_TRILHA: 'PROGRESSAO_PISTA_TRILHA',
  PROGRESSAO_RUMO_TRAVESSIA: 'PROGRESSAO_RUMO_TRAVESSIA',

  PROMESSA_ESCOTEIRA_SENIOR: 'PROMESSA_ESCOTEIRA_SENIOR',
  PROGRESSAO_SENIOR: 'PROGRESSAO_SENIOR',
  IMMA_SENIOR: 'IMMA_SENIOR',
  CONE_SUL_SENIOR: 'CONE_SUL_SENIOR',
  LUSOFONIA_SENIOR: 'LUSOFONIA_SENIOR',
  DESAFIO_COMUNITARIO: 'DESAFIO_COMUNITARIO',

  PROMESSA_ESCOTEIRA_PIONEIRO: 'PROMESSA_ESCOTEIRA_PIONEIRO',
  PROGRESSAO_LOBINHO: 'PROGRESSAO_LOBINHO',
  PROGRESSAO_ESCOTEIRO: 'PROGRESSAO_ESCOTEIRO',
  PROGRESSAO_PIONEIRO: 'PROGRESSAO_PIONEIRO',
}
