'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  PROMESSA_ESCOTEIRA_LOBINHO: 'PROMESSA_ESCOTEIRA_LOBINHO',
  PROMESSA_ESCOTEIRA_SENIOR: 'PROMESSA_ESCOTEIRA_SENIOR',
  PROMESSA_ESCOTEIRA_ESCOTEIRO: 'PROMESSA_ESCOTEIRA_SENIOR',
  PROMESSA_ESCOTEIRA_PIONEIRO: 'PROMESSA_ESCOTEIRA_PIONEIRO',

  ESCALADA: 'ESCALADA',
  CONQUISTA: 'CONQUISTA',
  AZIMUTE: 'AZIMUTE',
  IMMA_SENIOR: 'IMMA_SENIOR',
  CONE_SUL_SENIOR: 'CONE_SUL_SENIOR',
  LUSOFONIA_SENIOR: 'LUSOFONIA_SENIOR',
  DESAFIO_COMUNITARIO: 'DESAFIO_COMUNITARIO',
  MATEIRO: 'MATEIRO',
  AERONAUTA: 'AERONAUTA',
  NAVAL: 'NAVAL',
  CORDAO_DESAFIO_SENIOR: 'CORDAO_DESAFIO_SENIOR',
  CORDAO_DOURADO: 'CORDAO_DOURADO',
  ESCOTEIRO_PATRIA: 'ESCOTEIRO_PATRIA'
};