'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _create = require('./create');

var _create2 = _interopRequireDefault(_create);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = (0, _create2.default)(['ESPECIALIDADE', 'CULTURA', 'SERVICOS', 'CIENCIA_TECNOLOGIA', 'HABILIDADES_ESCOTEIRAS', 'DESPORTO', 'PROMESSA_ESCOTEIRA_LOBINHO', 'PROGRESSAO_PATATENRA_SALTADOR', 'PROGRESSAO_RASTREADOR_CACADOR', 'PROMESSA_ESCOTEIRA_ESCOTEIRO', 'PROGRESSAO_PISTA_TRILHA', 'PROGRESSAO_RUMO_TRAVESSIA', 'PROMESSA_ESCOTEIRA_SENIOR', 'PROGRESSAO_SENIOR', 'IMMA_SENIOR', 'CONE_SUL_SENIOR', 'LUSOFONIA_SENIOR', 'DESAFIO_COMUNITARIO', 'APRENDER_SENIOR', 'PROMESSA_ESCOTEIRA_PIONEIRO', 'PROGRESSAO_LOBINHO', 'PROGRESSAO_ESCOTEIRO', 'PROGRESSAO_PIONEIRO']);