'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _create = require('./create');

var _create2 = _interopRequireDefault(_create);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = (0, _create2.default)(['PROMESSA_ESCOTEIRA', 'ESPECIALIDADE', 'CULTURA', 'SERVICOS', 'CIENCIA_TECNOLOGIA', 'HABILIDADES_ESCOTEIRAS', 'DESPORTO', 'PROMESSA_ESCOTEIRA_LOBINHO', 'PROGRESSAO_PATATENRA_SALTADOR', 'PATATENRA', 'SALTADOR', 'RASTREADOR', 'CACADOR', 'PISTA', 'TRILHA', 'RUMO', 'TRAVESSIA', 'ESCALADA', 'CONQUISTA', 'AZIMUTE', 'COMPROMETIMENTO', 'CIDADANIA', 'PROGRESSAO_RASTREADOR_CACADOR', 'IMMA_LOBINHO', 'CONE_SUL_LOBINHO', 'LUSOFONIA_LOBINHO', 'BOA_ACAO', 'APRENDER_LOBINHO', 'PROMESSA_ESCOTEIRA_ESCOTEIRO', 'PROGRESSAO_PISTA_TRILHA', 'PROGRESSAO_RUMO_TRAVESSIA', 'CONE_SUL_ESCOTEIRO', 'IMMA_ESCOTEIRO', 'LUSOFONIA_ESCOTEIRO', 'ACAO_COMUNITARIA', 'APRENDER_ESCOTEIRO', 'PROMESSA_ESCOTEIRA_PIONEIRO', 'PROMESSA_ESCOTEIRA_SENIOR', 'PROGRESSAO_SENIOR', 'IMMA_SENIOR', 'CONE_SUL_SENIOR', 'LUSOFONIA_SENIOR', 'DESAFIO_COMUNITARIO', 'APRENDER_SENIOR', 'PROMESSA_ESCOTEIRA_PIONEIRO', 'PROGRESSAO_LOBINHO', 'PROGRESSAO_ESCOTEIRO', 'PROGRESSAO_PIONEIRO', 'CONE_SUL_PIONEIRO', 'LUSOFONIA_PIONEIRO', 'APRENDER_PIONEIRO']);