export default {
  INTRODUTORIO: 'INTRODUTORIO',
  PROGRESSAO: 'PROGRESSAO',
  INSIGNIA_ESPECIAL: 'INSIGNIA_ESPECIAL',
  CORDAO: 'CORDAO',
  INSIGNIA_MODALIDADE: 'INSIGNIA_MODALIDADE',
  GRAU_MAXIMO: 'GRAU_MAXIMO'
}
